rules:
- host: javawebappcal.mycluster.k8s.local
  http:
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: java-webappcal-service
          port:
            number: 80
