- name: Install AWS CLI
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Ensure unzip is installed
      yum:
        name: unzip
        state: present

    - name: Download AWS CLI installer
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
        mode: '0644'

    - name: Unzip AWS CLI installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install or update AWS CLI
      command: sudo /tmp/aws/install --update
