- name: Install AWS CLI
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install unzip
      package:
        name: unzip
        state: present

    - name: Download AWS CLI
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"

    - name: Unzip AWS CLI
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp"
        remote_src: yes

    - name: Install AWS CLI (with update flag)
      command: "sudo ./aws/install --update"
      args:
        chdir: "/tmp"
