- name: Install Kubectl
  hosts: all
  become: yes
  tasks:
    - name: Download kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.33.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'