- name: Install AWS CLI
  hosts: all
  become: yes
  tasks:
    - name: Install unzip
      yum:
        name: unzip
        state: present
    - name: Download AWS CLI
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
    - name: Unzip AWS CLI
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: yes
    - name: Install AWS CLI
      command: sudo ./aws/install chdir=/tmp
